os:
  - linux
language: cpp
sudo: false
cache: apt
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3

    packages:
    - autoconf
    - automake
    - bison
    - clang-3.8
    - cmake
    - cmake-data
    - flex
    - g++-5
    - git
    - lcov
    - libstdc++-5-dev
    - libtool
    - make
    - pkg-config
    - python-software-properties
    - wget
    - tex-info
    - python-dev
    - python-setuptools
    - python
    - swig

script:
  # compile dReal
  - export CXX=g++-5
  - export CC=gcc-5
  - mkdir build
  - cd build
  - CMAKE_CMD_OPTION="-DBUILD_SHARED_LIB=ON -DUSE_LOCAL_THIRD_PARTY=ON -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=${HOME}/dreal_bin/"
  - cmake $CMAKE_CMD_OPTION ../src
  - make
  - make install
  - cd ../src/api/
  - python setup.py build_ext --dreal-dir=${HOME}/dreal_bin build
  - ls ${HOME}
